services:
  kavita:
    image: lscr.io/linuxserver/kavita:latest
    container_name: kavita
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /home/sam/kavita:/config
      - /home/sam/hoard/books:/data:ro
    ports:
      - 5000:5000
    restart: unless-stopped