services:
  kiwix-js:
    image: nginx:alpine
    container_name: kiwix-js
    ports:
      - "8090:80"
    volumes:
      - /home/sam/kiwix-js-pwa/www:/usr/share/nginx/html:ro
      - /home/sam/hoard/ZimFiles:/data:ro
    restart: unless-stopped