# Taken from this site:
# https://awesome-docker-compose.com/apps/office-suites/bentopdf
services:
  bentopdf:
    image: ghcr.io/alam00000/bentopdf:latest
    container_name: bentopdf
    ports:
      - '3000:8080'
    restart: unless-stopped