services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION}

    volumes:
      # Immich internal managed library storage
      - ${UPLOAD_LOCATION}:/data

      # External archive import source (read-only)
      - "/home/sam/hoard/Photos Folder:/import:ro"

      # Host timezone
      - /etc/localtime:/etc/localtime:ro

    ports:
      - "2283:2283"

    depends_on:
      - redis
      - database

    restart: always


  redis:
    container_name: immich_redis
    image: docker.io/valkey/valkey:9
    restart: always


  database:
    container_name: immich_postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0

    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}

    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data

    restart: always
