services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:release

    volumes:
      # Immich internal library storage (managed copy)
      - /home/sam/immich-app/library:/data

      # External archive (read-only import source)
      - "/home/sam/hoard/Photos Folder:/import:ro"

      # Timezone
      - /etc/localtime:/etc/localtime:ro

    ports:
      - "2283:2283"

    depends_on:
      - redis
      - database

    restart: always


  redis:
    container_name: immich_redis
    image: docker.io/valkey/valkey:9
    restart: always


  database:
    container_name: immich_postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0

    environment:
      POSTGRES_PASSWORD: immichpassword
      POSTGRES_USER: immichuser
      POSTGRES_DB: immich

    volumes:
      - /home/sam/immich-app/db:/var/lib/postgresql/data

    restart: always
services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      # Immich internal uploads (new photos)
      - /home/sam/immich-app/library:/data
      # Host timezone
      - /etc/localtime:/etc/localtime:ro
      # External existing photos (read-only)
      - "/home/sam/hoard/Photos Folder:/external:ro"
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - /home/sam/immich-app/ml-cache:/cache
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/valkey/valkey:9@sha256:546304417feac0874c3dd576e0952c6bb8f06bb4093ea0c9ca303c73cf458f63
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0@sha256:bcf63357191b76a916ae5eb93464d65c07511da41e3bf7a8416db519b40b1c23
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - /home/sam/immich-app/db:/var/lib/postgresql/data
    shm_size: 128mb
    restart: always
    healthcheck:
      disable: false

volumes:
  model-cache:
