# This was obtained here:
# https://hub.docker.com/r/matszwe02/ytdlp_web_player

services:
    ytdlp_web_player:
        # build: .
        image: matszwe02/ytdlp_web_player
        restart: unless-stopped
        environment:
            - APP_TITLE=YT-DLP Player
            - THEME_COLOR=#ff7300
            - GENERATE_SPRITE_BELOW=1800 # video length in seconds
            - AMOLED_BG=false
        ports:
            - 5000:5000