---
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /home/sam/jellyfin:/config
      - /home/sam/hoard/Movies:/data/movies
    ports:
      - 8096:8096
    restart: unless-stopped
