version: '3.8'

services:
  kiwix-all:
    image: ghcr.io/kiwix/kiwix-serve:latest
    container_name: kiwix-all
    volumes:
      - /home/sam/hoard/ZimFiles/:/data/
    command: ["--port=8081", "--address=all", "/data/*.zim"]
    ports:
      - "8085:8081"
    restart: unless-stopped