version: '3.8'

services:
  kiwix-all:
    image: ghcr.io/kiwix/kiwix-serve:latest
    container_name: kiwix-all
    volumes:
      - /home/sam/hoard/ZimFiles/:/data/
    command: ["--address=all", "/data/*.zim"]
    # Map Host 8085 to Container 8080 (the default internal port)
    ports:
      - "8085:8080"
    restart: unless-stopped