---
services:
  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: syncthing
    hostname: syncthing
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - SYNCTHING_ARGS=-gui-address=0.0.0.0:8384
    volumes:
      - /home/sam/syncthing/config:/config
      - /home/sam/hoard:/hoard
      - /home/sam/hub:/hub
    ports:
      - 8384:8384        # GUI/API
      - 22000:22000/tcp  # Sync protocol TCP
      - 21027:21027/udp  # Local discovery
    restart: unless-stopped