---
services:
  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: syncthing
    hostname: syncthing
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - SYNCTHING_ARGS=-listen=0.0.0.0:22000
    volumes:
      - /home/sam/syncthing/config:/config
      - /home/sam/hoard:/hoard
      - /home/sam/hub:/hub
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: unless-stopped