version: "3.8"

services:
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy:15
    container_name: wg-easy
    environment:
      - WG_HOST=${WG_HOST}       # e.g., vpn.sambanya.com
      - PASSWORD=${PASSWORD}     # wg-easy admin password
      - INSECURE=false           # ensures HTTPS for wg-easy
      - WG_PORT=51820
    volumes:
      - ./wg-data:/etc/wireguard
      - /lib/modules:/lib/modules:ro
    ports:
      - "51820:51820/udp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.forwarding=1
    networks:
      - wg

  caddy:
    image: caddy:latest
    container_name: caddy
    environment:
      - BASIC_USER=${BASIC_USER}   # username for basic auth
      - BASIC_PASS=${BASIC_PASS}   # password (to hash manually)
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/sam/caddy/Caddyfile:/etc/caddy/Caddyfile
      - /home/sam/caddy/caddy-data:/data
      - /home/sam/caddy/caddy-config:/config
    restart: unless-stopped
    networks:
      - wg

networks:
  wg:
    driver: bridge
    enable_ipv6: true